M48
; DRILL file {KiCad (6.0.4)} date Mon May  2 14:31:16 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-02T14:31:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.25Y-1.975
X3.25Y-5.575
X6.85Y-1.975
X6.85Y-5.575
T0
M30
